### ISSUE TITLE
Kotlin ile ilgili kaynaklar

### ISSUE THREAD

**Issue by halilozel1903** [AndroidEduIO/AndroidSources#2]
Kotlin çalışırken yararlandığım ve hoşuma giden siteleri ve kaynakları aşağıda sıraladım : 

**Tutorial - Blog Yazıları**

- https://www.programiz.com/kotlin-programming#tutorial
- https://www.javatpoint.com/kotlin-inline-function
-  https://www.mobilhanem.com/kotlin-egitimleri/

<br>

**Yazılı Kaynak - Kitap**

Kitap Kotlin tarafından kaynak olarak gösteriliyor. Sitesinde kaynakça bölümünde bulunuyor.

- https://www.dr.com.tr/kitap/kotlin/mehmet-ali-sicak/egitim-basvuru/bilgisayar/urunno=0001711226001

<br>

**Videolu Eğitimler**

Bu eğitim sıfırdan Kotlin ile öğrenmeye başlanıp ileri seviyeye kadar gidip güzel applerin yapıldığı bir ders serisidir.

-  https://www.udemy.com/sifirdan-ileri-seviyeye-kotlin-ve-android-kursu/learn/v4/

<br>

Aklıma ilk etapta gelen kaynaklar bunlar buldukça ve aklıma geldikçe yine issue açarım 👍

**Comment by AndroidEduIO** [comment]
Bunları pr olarak açman lazım. issue olarak değil. Yine de buradaki linkleri inceleyerek uygun olanları source'a ekleyeceğim.
